CC     = gcc
OBJS   = my_c.o linked_list.o
CFLAGS = -g3 -Wall -Wextra -O0 # -W* for warnings, -g3 for maximum debug, -O0 for no optimization

all: head tail

head: $(OBJS) head.o
	$(CC) $(CFLAGS) -o $@ $^

tail: $(OBJS) tail.o
	$(CC) $(CFLAGS) -o $@ $^

# deletes files generated by compilation
clean:
	rm -f *.o head tail

run-h: head
	./head

run-t: tail
	./tail

my_c.o: my_c.c
linked_list.o: linked_list.c linked_list.h my_c.h
head.o: head.c linked_list.h my_c.h
tail.o: tail.c linked_list.h my_c.h

