CC     = gcc
OBJS   = my_c.o linked_list.o
# -W* for warnings, -g3 for maximum debug, -O0 for no optimization
CFLAGS = -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wstrict-prototypes -Wwrite-strings -Waggregate-return \
         -Wcast-qual -Wswitch-default -Wswitch-enum -Wconversion -Wunreachable-code -Wfloat-equal -g3 -O0

all: head tail

head: $(OBJS) head.o
	$(CC) $(CFLAGS) -o $@ $^

tail: $(OBJS) tail.o
	$(CC) $(CFLAGS) -o $@ $^

# deletes files generated by compilation
clean:
	rm -f *.o head tail

run-h: head
	./head

run-t: tail
	./tail

my_c.o: my_c.c
linked_list.o: linked_list.c linked_list.h my_c.h
head.o: head.c linked_list.h my_c.h
tail.o: tail.c linked_list.h my_c.h

