CC     = gcc
OBJS   = my_c.o
CFLAGS = -Wall -O0 # -Wall for warnings, -g for debug, -O0 for no optimization

all: head tail

head: $(OBJS) head.o
	$(CC) $(CFLAGS) -o $@ $^

tail: $(OBJS) history.o tail.o
	$(CC) $(CFLAGS) -o $@ $^

# deletes files generated by compilation
clean:
	rm -f *.o head tail

run-h: head
	./head

run-t: tail
	./tail

my_c.o: my_c.c
history.o: history.c history.h my_c.h
head.o: head.c my_c.h
tail.o: tail.c history.h my_c.h
